name: Build azul-prime-8
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - java/azul-prime-8/*
      - java/entrypoint.sh
      - .github/workflows/azul-prime-8.yml
jobs:
  push:
    name: "azul-prime-8"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./java
          file: ./java/azul-prime-8/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mysticminemc/images:azul-prime-8
